### ISSUE TITLE
构建 YOLOV6 的 TensorRT 文件时出了问题，求大佬帮忙

### ISSUE THREAD

**Issue by sha-mao** [Yutong-gannis/ETSAuto#12]
Error Code 1: Cudnn (CUDNN_STATUS_EXECUTION_FAILED)
Traceback (most recent call last):
  File "./tools/export.py", line 288, in <module>
    main(args)
  File "./tools/export.py", line 249, in main
    builder.create_engine(args.engine, args.precision, args.calib_input, args.calib_cache, args.calib_num_images,
  File "./tools/export.py", line 242, in create_engine
    with self.builder.build_engine(self.network, self.config) as engine, open(engine_path, "wb") as f:
AttributeError: __enter__

**Comment by Yutong-gannis** [comment]
@sha-mao 检查一下CUDA CUDNN版本是否匹配
