### ISSUE TITLE
不知道什么问题有大佬帮忙看看吗？

### ISSUE THREAD

**Issue by Childish-Ghost** [Yutong-gannis/ETSAuto#22]
base) D:\Self-driving-Truck-in-Euro-Truck-Simulator2-main>python ./tools/export.py -o ./engines/yolov6s_bdd_60.onnx -e ./engines/yolov6s_bdd_60.engine --end2end -p fp32
Namespace(calib_batch_size=8, calib_cache='./calibration.cache', calib_input=None, calib_num_images=5000, conf_thres=0.4, end2end=True, engine='./engines/yolov6s_bdd_60.engine', iou_thres=0.5, max_det=100, onnx='./engines/yolov6s_bdd_60.onnx', precision='fp32', verbose=False, workspace=1)
[03/16/2023-19:16:06] [TRT] [I] [MemUsageChange] Init CUDA: CPU +35, GPU +0, now: CPU 8247, GPU 1161 (MiB)
[03/16/2023-19:16:14] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU -15, GPU +0, now: CPU 8280, GPU 1161 (MiB)
./tools/export.py:109: DeprecationWarning: Use set_memory_pool_limit instead.
  self.config.max_workspace_size = workspace * (2 ** 30)
[03/16/2023-19:16:14] [TRT] [W] onnx2trt_utils.cpp:369: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
Network Description
Input 'images' with shape (1, 3, 640, 640) and dtype DataType.FLOAT
Output 'outputs' with shape (1, 8400, 15) and dtype DataType.FLOAT
./tools/export.py:143: DeprecationWarning: Use network created with NetworkDefinitionCreationFlag::EXPLICIT_BATCH flag instead.
  self.builder.max_batch_size = self.batch_size
Building fp32 Engine in D:\Self-driving-Truck-in-Euro-Truck-Simulator2-main\engines\yolov6s_bdd_60.engine
./tools/export.py:242: DeprecationWarning: Use build_serialized_network instead.
  with self.builder.build_engine(self.network, self.config) as engine, open(engine_path, "wb") as f:
[03/16/2023-19:17:21] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU -111, GPU +52, now: CPU 8185, GPU 1213 (MiB)
[03/16/2023-19:17:21] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +1, GPU +10, now: CPU 8186, GPU 1223 (MiB)
[03/16/2023-19:17:21] [TRT] [I] Local timing cache in use. Profiling results in this builder pass will not be stored.
[03/16/2023-19:17:29] [TRT] [E] 1: [convolutionRunner.cpp::nvinfer1::rt::cuda::CudnnConvolutionRunner::executeConv::465] Error Code 1: Cudnn (CUDNN_STATUS_EXECUTION_FAILED)
Traceback (most recent call last):
  File "./tools/export.py", line 288, in <module>
    main(args)
  File "./tools/export.py", line 249, in main
    builder.create_engine(args.engine, args.precision, args.calib_input, args.calib_cache, args.calib_num_images,
  File "./tools/export.py", line 242, in create_engine
    with self.builder.build_engine(self.network, self.config) as engine, open(engine_path, "wb") as f:
AttributeError: __enter__

**Comment by Yutong-gannis** [comment]
@Childish-Ghost `[convolutionRunner.cpp::nvinfer1::rt::cuda::CudnnConvolutionRunner::executeConv::465] Error Code 1: Cudnn (CUDNN_STATUS_EXECUTION_FAILED)`这个报错很大可能是cuda, cudnn, tensorrt这三个版本问题，你用的是什么版本。

**Comment by Childish-Ghost** [comment]
10
8

**Comment by Childish-Ghost** [comment]
CUDA 10.2 + cuDNN 8.7.0 + TensorRT 8.4.2.4

**Comment by Yutong-gannis** [comment]
试试fp16行不行

**Comment by Childish-Ghost** [comment]
我打算试试11的版本行不行
        
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
    
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            Yutong ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年3月16日 20:33
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            State ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [Yutong-gannis/Self-driving-Truck-in-Euro-Truck-Simulator2] 不知道什么问题有大佬帮忙看看吗？ (Issue #22)
        
      
    
  

试试fp16行不行

**Comment by Yutong-gannis** [comment]
用trtexec试试，另一个contributor用的就是这个方法
